# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: ProjectBuild
  jobs:
  - job : build
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
- stage : UnitTest
  jobs:
  - job : UnitTestJob
    steps :    
    - bash: echo "Unit Test 1"
  - job : UnitTest2Job
    steps :    
    - bash: echo "Unit Test 2"
- stage : DeployDev
  dependsOn: UnitTest
  # condition: and(succeeded(),)
  jobs:
  - job : DeployDevJob
    steps :    
    - bash: echo "Deploy in Dev"
- stage : DeployQA
  dependsOn: UnitTest
  jobs:
  - job : DeployQAJob
    steps :    
    - bash: echo "Deploy in QA"
